site_name: ODE Filters
site_url: https://paufisch.github.io/ode_filters/
repo_url: https://github.com/paufisch/ode_filters
docs_dir: docs
theme:
  name: material
plugins:
  - search
  - mkdocs-jupyter:
      execute: true
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - Examples:
      - Basic usage: examples/examples.ipynb
  - API Reference: api/index.md
