site_name: ODE Filters
site_url: https://paufisch.github.io/ode_filters/
repo_url: https://github.com/paufisch/ode_filters
docs_dir: docs
theme:
  name: material
plugins:
  - search
  - mkdocs-jupyter:
      execute: true
nav:
  - Home: index.md
  - Examples:
      - Probabilistic Solver Walkthrough: examples/examples.ipynb
